# canopen parameter
can_module: PCAN
can_baudrate: 1000
max_accelerations: [0.8,0.8,0.8]

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
frequency: 68

joint_names: [head_powerball_bottom_joint, head_powerball_side_joint]
module_ids: [7,8]
devices: ["/dev/pcan32", "/dev/pcan32"]
